# Cutiefetch Configuration
logo: "hot_cat"
colors:
  primary_label: "&p"
  primary_info: "&w"
modules:
  - { id: "os", label: "OS", enabled: true }
  - { id: "host", label: "Host", enabled: true }
  - { id: "kernel", label: "Kernel", enabled: true }
  - { id: "uptime", label: "Uptime", enabled: true }
  - { id: "pkgs", label: "Packages", enabled: true }
  - { id: "shell", label: "Shell", enabled: true }
  - { id: "cpu", label: "CPU", enabled: true }
  - { id: "gpu", label: "GPU", enabled: true }
  - { id: "mem", label: "Memory", enabled: true }
  - { id: "batt", label: "Power", enabled: true }